apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: projects-notes
  name: notes-ingress-name
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - notes.asimt.sa
        - asim.asimt.sa
        - asimt.sa
      secretName: cluster-issuer-certificate-notes
  rules:
    - host: notes.asimt.sa
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: notes-service-name
              port: 
                number: 80
