apiVersion: v1
kind: Service
metadata:
  name: whoami-test
  namespace: notes-ns-2
  labels:
    my: test-ingress
spec:
  type: ClusterIP
  selector:
    my: test-ingress
    type: main
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
