name: Add New Release

on:
  push:
    branches:
      - "main"

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add new Release
        run: >
          gh release create 
          $(gh release view --json tagName -q ".tagName" | awk -F. -v OFS=. '{$NF += 1 ; print}')
          --notes "TTTTTTTTTTT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
