name: Add New Release
on:
  push:
    branches:
      - main
jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increment latest version number
        run: gh release view --json tagName -q ".tagName" | awk -F. '{$3 += 1 ; print $1 "." $2 "." $3 ".alpha"}' > version.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat version.txt
      - run: gh release list --json tagName
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add new Release
        run: gh release create $(cat version.txt) --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
