name: Add New Release

on:
  push:
    branches:
      - "production"

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Increment latest version number
        run: gh release view --json tagName -q ".tagName" | awk -F. '{$3 += 1 ; print $1 "." $2 "." $3}' > version.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add new Release
        run: gh release create $(cat version.txt) --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
