name: Add New Release
on:
  push:
    branches:
      - production
jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increment latest version number
        run: gh release list --exclude-drafts | awk -F '\t' '{print $1}' | head -n 1 | awk -F. '{$3 += 1 ; print $1 "." $2 "." $3}' > version.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat version.txt
      - name: Add new Release
        run: gh release create $(cat version.txt)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
