name: Add New Release

on:
  push:
    branches:
      - "main"

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: gh release view
      - run: gh release view -q ".tag_name" 
      - name: Increment latest version number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh api
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          /repos/asim3/notes/releases/latest 
          | jq -r ".tag_name" 
          | awk -F. -v OFS=. '{$NF += 1 ; print}'
          > release.txt
      - name: Make Production Paths
        run: make
      - name: Add new Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $(cat release.txt) --notes "RRRRRRRRRRRRR"
          gh api
          --method POST
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          /repos/asim3/notes/releases
          -f tag_name=$(cat release.txt)
          -f target_commitish='production'
          -f name=Nnnnnn $(cat release.txt)
          -f body='Ddddddddddddddescription of the release'
          -F prerelease=true
          -F draft=false
          -F generate_release_notes=false 
