name: Add New Release

on:
  push:
    branches:
      - "main"

jobs:
  New_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh api
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          /repos/asim3/notes/releases/latest
      - name: Make Production Paths
        run: make
      - name: Add new Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh api
            --method POST
            -H "Accept: application/vnd.github+json"
            -H "X-GitHub-Api-Version: 2022-11-28"
            /repos/asim3/notes/releases
            -f tag_name='v1.0.0'
          -f target_commitish='production'
          -f name='v0.0.0.1'
          -f body='Ddddddddddddddescription of the release'
          -F prerelease=true
          -F draft=false
          -F generate_release_notes=false 
