name: Default environment variables
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs

on:
  push:
    tags:
      - v-**

jobs:
  print-all:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF_NAME}
      - run: echo ${GITHUB_REF_NAME:2}
