name: Default environment variables

on: workflow_dispatch


jobs:
  print-all:
    runs-on: ubuntu-latest
    steps:
      - run: echo $AAAAAAAAAA
        env:
          AAAAAAAAAA: ${{ inputs }}
      - run: echo ${{ inputs }}
