name: Update all init files

on:
  push:
    branches:
      - 'main'
      - 'releases/**'


jobs:
  update_init_HTML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make
