name: Update all init files

on:
  push:
    branches:
      - "main"

jobs:
  update_init_HTML:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make Production Paths
        run: make
